name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  # Build and run ci tests
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build with Next.js
        run: npm run build
      - name: Execute linter
        run: npm run lint
      - name: Execute CI tests
        run: npm run test:ci
